#!/usr/bin/env python3
"""Generate the agent-facing script index INTO a consumer project.

The installed layout does not match this repo's layout, and command names do not
predict script names (`/speckit-git-feature` runs `create-new-feature.sh`). An agent
working in a consumer project cannot see this repo's CLAUDE.md, so the mapping has to
travel with the install. Writes two files, both regenerated on every `install.sh --force`:

  <project>/.specify/extensions/AGENTS.md    command -> script table + layout rules
  <project>/.specify/scripts/bash/README.md  breadcrumb in the flat core tree

Usage: gen-agent-index.py <repo-dir> <project-dir>
Stdlib only.
"""
import glob, os, re, sys

GENERATED = "<!-- generated by speckit-squads gen-agent-index.py — do not edit -->"


def scripts_block(text):
    m = re.search(r'^provides:[ \t]*$\n(.*?)(?=^\S)', text + "\n\x00", re.M | re.S)
    if not m:
        return ""
    s = re.search(r'^  scripts:[ \t]*$\n(.*?)(?=^  \S|\Z)', m.group(1), re.M | re.S)
    return s.group(1) if s else ""


def entries(block):
    """Yield (file, command|None) per `- name:` entry, in declaration order."""
    cur = {}
    for line in block.split("\n"):
        s = line.strip()
        if s.startswith("- name:"):
            if cur.get("file"):
                yield cur["file"], cur.get("command")
            cur = {}
        for key in ("file", "command"):
            m = re.match(rf'-?\s*{key}:\s*["\']?([^"\'\s]+)', s)
            if m:
                cur[key] = m.group(1)
    if cur.get("file"):
        yield cur["file"], cur.get("command")


def collect(repo):
    owned, shared = [], []
    for kind, manifest in (("extensions", "extension.yml"), ("presets", "preset.yml")):
        for path in sorted(glob.glob(os.path.join(repo, kind, "*", manifest))):
            oid = os.path.basename(os.path.dirname(path))
            with open(path) as fh:
                block = scripts_block(fh.read())
            for rel, cmd in entries(block):
                installed = f".specify/{kind}/{oid}/{rel}"
                (owned if cmd else shared).append((cmd, installed, kind, oid))
    owned.sort(key=lambda r: (r[0], r[1]))
    shared.sort(key=lambda r: r[1])
    return owned, shared


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen-agent-index.py <repo-dir> <project-dir>")
    repo, project = sys.argv[1], sys.argv[2]
    owned, shared = collect(repo)

    rows = "\n".join(
        f"| `/{cmd.replace('.', '-')}` | `{path}` |" for cmd, path, _, _ in owned)
    lib = "\n".join(f"- `{path}`" for _, path, _, _ in shared)

    index = f"""{GENERATED}
# Extension & preset scripts — where they actually live

**Do not guess a script path.** Command names do not predict script names:
`/speckit-git-feature` runs `create-new-feature.sh`, not `feature.sh`.

## Layout

There are two script trees, and they never merge:

```
.specify/scripts/bash/                  core Spec Kit only — FLAT, no subdirectories
.specify/extensions/<id>/scripts/...    one tree per extension
.specify/presets/<id>/scripts/...       one tree per preset
```

`.specify/scripts/bash/<extension-id>/` does not exist and never will — `specify`
copies each extension whole into `.specify/extensions/<id>/` and never merges its
scripts into the core tree. Note also that `create-new-feature.sh` exists in *both*
trees as two different files.

## Command → script

| command | script |
| --- | --- |
{rows}

## Libraries and shared scripts

Sourced or shared by the above; no single command owns them.

{lib}

Regenerate with `./install.sh --force <project>` from the speckit-squads repo.
"""

    breadcrumb = f"""{GENERATED}
# This is the core Spec Kit script tree — it is FLAT

Extension and preset scripts are **not** here and never will be. There is no
`<extension-id>/` subdirectory in this tree.

Look in `.specify/extensions/<id>/scripts/bash/` or `.specify/presets/<id>/scripts/bash/`.
The full command → script table is at `.specify/extensions/AGENTS.md`.
"""

    wrote = []
    for rel, body in ((".specify/extensions/AGENTS.md", index),
                      (".specify/scripts/bash/README.md", breadcrumb)):
        dest = os.path.join(project, rel)
        if not os.path.isdir(os.path.dirname(dest)):
            continue
        with open(dest, "w") as fh:
            fh.write(body)
        wrote.append(rel)
    print(f"agent script index: wrote {', '.join(wrote)} ({len(owned)} commands mapped)")


if __name__ == "__main__":
    main()
