#!/usr/bin/env bash
# Uninstall every extension and preset shipped in this repo from a Spec Kit
# project. Only items present in the project's registry are removed; missing
# ones are skipped silently.
#
# This only de-registers the items from <project-dir>/.specify/ — it does
# NOT delete or modify the source files in this repo. Re-run install.sh to
# re-register.
#
# Usage:
#   ./uninstall.sh <project-dir>    # uninstall from the given Spec Kit project
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ $# -lt 1 || -z "${1:-}" ]]; then
  echo "usage: $(basename "$0") <project-dir>" >&2
  exit 2
fi
PROJECT_DIR="$1"

if [[ ! -d "$PROJECT_DIR/.specify" ]]; then
  echo "error: $PROJECT_DIR is not a Spec Kit project (.specify/ missing)" >&2
  exit 1
fi

# Absolute from here on: the script cds into the project, and pre-uninstall.sh is
# handed this path afterwards.
PROJECT_DIR="$(cd "$PROJECT_DIR" && pwd)"
cd "$PROJECT_DIR"

shopt -s nullglob

# Harness-level wiring that install.sh's post-install step added (.claude/settings.json
# entries, CLAUDE.md blocks) is outside `specify`'s reach, so it has to come out
# before the item is de-registered — its script lives in the item's own tree.
# Auto-discovered; there is no list to maintain.
for item_dir in "$REPO_DIR"/extensions/*/ "$REPO_DIR"/presets/*/; do
  pre="$item_dir/scripts/bash/pre-uninstall.sh"
  [[ -x "$pre" ]] || continue
  echo "==> pre-uninstall: $(basename "$item_dir")"
  "$pre" "$PROJECT_DIR" || true
done

for ext_dir in "$REPO_DIR"/extensions/*/; do
  [[ -f "$ext_dir/extension.yml" ]] || continue
  name="$(basename "$ext_dir")"
  echo "==> extension: $name"
  yes | specify extension remove "$name" 2>&1 | tail -3 || true
done

for preset_dir in "$REPO_DIR"/presets/*/; do
  [[ -f "$preset_dir/preset.yml" ]] || continue
  name="$(basename "$preset_dir")"
  echo "==> preset: $name"
  yes | specify preset remove "$name" 2>&1 | tail -3 || true
done

# Remove the generated agent script index (install.sh writes it; it describes
# only this repo's extensions, so it must not outlive them).
for f in .specify/extensions/AGENTS.md .specify/scripts/bash/README.md; do
  if [[ -f "$f" ]] && head -1 "$f" | grep -q "generated by speckit-squads"; then
    rm -f "$f"
    echo "==> removed $f"
  fi
done

echo
echo "Done. Uninstalled from: $PROJECT_DIR"
